// <auto-generated />
using System;
using HealLink.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealLink.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HealLinkDbContext))]
    [Migration("20250717042453_HealLinkDataBaseV1.3_User__Admin")]
    partial class HealLinkDataBaseV13_User__Admin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealLink.Domain.Admins.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("HealLink.Domain.Doctors.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedByAdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("NationalID")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PracticeLicenseNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SyndicateIdImageLink")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByAdminId");

                    b.ToTable("Doctors", (string)null);
                });

            modelBuilder.Entity("HealLink.Domain.MedicalHistories.MedicalHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("FileLink")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_MedicalHistories_PatientId");

                    b.ToTable("MedicalHistories", (string)null);
                });

            modelBuilder.Entity("HealLink.Domain.PatientDoctorSubscriptionChatMessages.PatientDoctorSubscriptionChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFromPatient")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)");

                    b.Property<Guid>("PatientDoctorSubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PatientDoctorSubscriptionId")
                        .HasDatabaseName("IX_SubscriptionChatMessages_SubscriptionId");

                    b.ToTable("SubscriptionChatMessages", (string)null);
                });

            modelBuilder.Entity("HealLink.Domain.PatientDoctorSubscriptions.PatientDoctorSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SubscribedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("IX_PatientDoctorSubscriptions_DoctorId");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_PatientDoctorSubscriptions_PatientId");

                    b.ToTable("PatientDoctorSubscriptions", (string)null);
                });

            modelBuilder.Entity("HealLink.Domain.Patients.HealLink.Domain.Patients.PatientGuardian", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GuardianId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RelationshipType")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("GuardianId")
                        .HasDatabaseName("IX_PatientGuardians_GuardianId");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_PatientGuardians_PatientId");

                    b.ToTable("PatientGuardians", (string)null);
                });

            modelBuilder.Entity("HealLink.Domain.Patients.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Patients", (string)null);
                });

            modelBuilder.Entity("HealLink.Domain.Payments.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("DoctorRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DoneAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentProviderId")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorRequestId")
                        .IsUnique();

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("HealLink.Domain.Prescriptions.Medication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PrescriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("TimesPerDay")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("PrescriptionId")
                        .HasDatabaseName("IX_Medications_PrescriptionId");

                    b.ToTable("Medications", (string)null);
                });

            modelBuilder.Entity("HealLink.Domain.Prescriptions.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PrescriptionText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("SubsciptionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubsciptionId");

                    b.ToTable("Prescriptions", (string)null);
                });

            modelBuilder.Entity("HealLink.Domain.Requests.DoctorRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttachedFileLink")
                        .HasMaxLength(12000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DecisionDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsAccepted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("SenderId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("DoctorRequests");
                });

            modelBuilder.Entity("HealLink.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("NameToShow")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProfilePhotoLink")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("_passwordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("PasswordHash");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HealLink.Domain.Admins.Admin", b =>
                {
                    b.HasOne("HealLink.Domain.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("HealLink.Domain.Admins.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealLink.Domain.Doctors.Doctor", b =>
                {
                    b.HasOne("HealLink.Domain.Admins.Admin", "Admin")
                        .WithMany("_ApprovedDoctors")
                        .HasForeignKey("ApprovedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealLink.Domain.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("HealLink.Domain.Doctors.Doctor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealLink.Domain.MedicalHistories.MedicalHistory", b =>
                {
                    b.HasOne("HealLink.Domain.Patients.Patient", "Patient")
                        .WithMany("MedicalHistories")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealLink.Domain.PatientDoctorSubscriptionChatMessages.PatientDoctorSubscriptionChatMessage", b =>
                {
                    b.HasOne("HealLink.Domain.PatientDoctorSubscriptions.PatientDoctorSubscription", "PatientDoctorSubscription")
                        .WithMany("ChatMassages")
                        .HasForeignKey("PatientDoctorSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatientDoctorSubscription");
                });

            modelBuilder.Entity("HealLink.Domain.PatientDoctorSubscriptions.PatientDoctorSubscription", b =>
                {
                    b.HasOne("HealLink.Domain.Doctors.Doctor", "Doctor")
                        .WithMany("Subscriptions")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealLink.Domain.Patients.Patient", "Patient")
                        .WithMany("DoctorPatients")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealLink.Domain.Patients.HealLink.Domain.Patients.PatientGuardian", b =>
                {
                    b.HasOne("HealLink.Domain.Patients.Patient", "Guardian")
                        .WithMany()
                        .HasForeignKey("GuardianId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealLink.Domain.Patients.Patient", "Patient")
                        .WithMany("Guardians")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Guardian");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealLink.Domain.Patients.Patient", b =>
                {
                    b.HasOne("HealLink.Domain.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("HealLink.Domain.Patients.Patient", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealLink.Domain.Payments.Payment", b =>
                {
                    b.HasOne("HealLink.Domain.Requests.DoctorRequest", "DoctorRequest")
                        .WithOne("Payment")
                        .HasForeignKey("HealLink.Domain.Payments.Payment", "DoctorRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoctorRequest");
                });

            modelBuilder.Entity("HealLink.Domain.Prescriptions.Medication", b =>
                {
                    b.HasOne("HealLink.Domain.Prescriptions.Prescription", "Prescription")
                        .WithMany("Medications")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("HealLink.Domain.Prescriptions.Prescription", b =>
                {
                    b.HasOne("HealLink.Domain.PatientDoctorSubscriptions.PatientDoctorSubscription", "Subscription")
                        .WithMany("Prescriptions")
                        .HasForeignKey("SubsciptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("HealLink.Domain.Requests.DoctorRequest", b =>
                {
                    b.HasOne("HealLink.Domain.Doctors.Doctor", "Doctor")
                        .WithMany("DoctorRequests")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealLink.Domain.Patients.Patient", "Sender")
                        .WithMany("DoctorRequests")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealLink.Domain.PatientDoctorSubscriptions.PatientDoctorSubscription", "Subscription")
                        .WithMany("DoctorRequests")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Doctor");

                    b.Navigation("Sender");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("HealLink.Domain.Admins.Admin", b =>
                {
                    b.Navigation("_ApprovedDoctors");
                });

            modelBuilder.Entity("HealLink.Domain.Doctors.Doctor", b =>
                {
                    b.Navigation("DoctorRequests");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("HealLink.Domain.PatientDoctorSubscriptions.PatientDoctorSubscription", b =>
                {
                    b.Navigation("ChatMassages");

                    b.Navigation("DoctorRequests");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("HealLink.Domain.Patients.Patient", b =>
                {
                    b.Navigation("DoctorPatients");

                    b.Navigation("DoctorRequests");

                    b.Navigation("Guardians");

                    b.Navigation("MedicalHistories");
                });

            modelBuilder.Entity("HealLink.Domain.Prescriptions.Prescription", b =>
                {
                    b.Navigation("Medications");
                });

            modelBuilder.Entity("HealLink.Domain.Requests.DoctorRequest", b =>
                {
                    b.Navigation("Payment")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
